/* AUTO GENERATED FILE - DO NOT EDIT! */

import { registerComponent, registerModuleDeferred, registerMethod } from "../app";
import { lazy } from "react";
import { notification, message, Modal } from 'antd';
export function register() {
  registerModuleDeferred("antd", async () => {
    registerComponent('Result', '', lazy(() => import("../fragments/antd/result.tsx")), 'antd', true)
    registerComponent('TreeSelect', '', lazy(() => import("../fragments/antd/treeselect.tsx")), 'antd', false)
    registerComponent('App', '', lazy(() => import("../fragments/antd/app.tsx")), 'antd', true)
    registerComponent('Modal', '', lazy(() => import("../fragments/antd/modal.tsx")), 'antd', true)
    registerComponent('Segmented', '', lazy(() => import("../fragments/antd/segmented.tsx")), 'antd', true)
    registerComponent('ColorPicker', '', lazy(() => import("../fragments/antd/colorpicker.tsx")), 'antd', true)
    registerComponent('Switch', '', lazy(() => import("../fragments/antd/switch.tsx")), 'antd', true)
    registerComponent('Mentions', '', lazy(() => import("../fragments/antd/mentions.tsx")), 'antd', true)
    registerComponent('Anchor', '', lazy(() => import("../fragments/antd/anchor.tsx")), 'antd', true)
    registerComponent('Drawer', '', lazy(() => import("../fragments/antd/drawer.tsx")), 'antd', true)
    registerComponent('Descriptions', '', lazy(() => import("../fragments/antd/descriptions.tsx")), 'antd', true)
    registerComponent('Upload', '', lazy(() => import("../fragments/antd/upload.tsx")), 'antd', true)
    registerComponent('Space', '', lazy(() => import("../fragments/antd/space.tsx")), 'antd', true)
    registerComponent('Empty', '', lazy(() => import("../fragments/antd/empty.tsx")), 'antd', true)
    registerComponent('Divider', '', lazy(() => import("../fragments/antd/divider.tsx")), 'antd', true)
    registerComponent('Collapse', '', lazy(() => import("../fragments/antd/collapse.tsx")), 'antd', true)
    registerComponent('Alert', '', lazy(() => import("../fragments/antd/alert.tsx")), 'antd', true)
    registerComponent('Typography', '', lazy(() => import("../fragments/antd/typography.tsx")), 'antd', true)
    registerComponent('Popconfirm', '', lazy(() => import("../fragments/antd/popconfirm.tsx")), 'antd', true)
    registerComponent('Slider', '', lazy(() => import("../fragments/antd/slider.tsx")), 'antd', true)
    registerComponent('Rate', '', lazy(() => import("../fragments/antd/rate.tsx")), 'antd', true)
    registerComponent('Input', '', lazy(() => import("../fragments/antd/input.tsx")), 'antd', true)
    registerComponent('Dropdown', '', lazy(() => import("../fragments/antd/dropdown.tsx")), 'antd', true)
    registerComponent('Cascader', '', lazy(() => import("../fragments/antd/cascader.tsx")), 'antd', true)
    registerComponent('Tour', '', lazy(() => import("../fragments/antd/tour.tsx")), 'antd', true)
    registerComponent('Tooltip', '', lazy(() => import("../fragments/antd/tooltip.tsx")), 'antd', true)
    registerComponent('Transfer', '', lazy(() => import("../fragments/antd/transfer.tsx")), 'antd', true)
    registerComponent('Breadcrumb', '', lazy(() => import("../fragments/antd/breadcrumb.tsx")), 'antd', true)
    registerComponent('FloatButton', '', lazy(() => import("../fragments/antd/floatbutton.tsx")), 'antd', true)
    registerComponent('Layout', '', lazy(() => import("../fragments/antd/layout.tsx")), 'antd', true)
    registerComponent('Table', '', lazy(() => import("../fragments/antd/table.tsx")), 'antd', true)
    registerComponent('Popover', '', lazy(() => import("../fragments/antd/popover.tsx")), 'antd', true)
    registerComponent('Flex', '', lazy(() => import("../fragments/antd/flex.tsx")), 'antd', true)
    registerComponent('Tag', '', lazy(() => import("../fragments/antd/tag.tsx")), 'antd', true)
    registerComponent('Progress', '', lazy(() => import("../fragments/antd/progress.tsx")), 'antd', true)
    registerComponent('DatePicker', '', lazy(() => import("../fragments/antd/datepicker.tsx")), 'antd', true)
    registerComponent('Avatar', '', lazy(() => import("../fragments/antd/avatar.tsx")), 'antd', true)
    registerComponent('Tabs', '', lazy(() => import("../fragments/antd/tabs.tsx")), 'antd', true)
    registerComponent('Skeleton', '', lazy(() => import("../fragments/antd/skeleton.tsx")), 'antd', true)
    registerComponent('List', '', lazy(() => import("../fragments/antd/list.tsx")), 'antd', true)
    registerComponent('Radio', '', lazy(() => import("../fragments/antd/radio.tsx")), 'antd', true)
    registerComponent('AutoComplete', '', lazy(() => import("../fragments/antd/autocomplete.tsx")), 'antd', true)
    registerComponent('TimePicker', '', lazy(() => import("../fragments/antd/timepicker.tsx")), 'antd', true)
    registerComponent('Steps', '', lazy(() => import("../fragments/antd/steps.tsx")), 'antd', true)
    registerComponent('QRCode', '', lazy(() => import("../fragments/antd/qrcode.tsx")), 'antd', true)
    registerComponent('Checkbox', '', lazy(() => import("../fragments/antd/checkbox.tsx")), 'antd', true)
    registerComponent('Button', '', lazy(() => import("../fragments/antd/button.tsx")), 'antd', true)
    registerComponent('Statistic', '', lazy(() => import("../fragments/antd/statistic.tsx")), 'antd', true)
    registerComponent('Menu', '', lazy(() => import("../fragments/antd/menu.tsx")), 'antd', true)
    registerComponent('Col', '', lazy(() => import("../fragments/antd/col.tsx")), 'antd', true)
    registerComponent('Row', '', lazy(() => import("../fragments/antd/row.tsx")), 'antd', true)
    registerComponent('Timeline', '', lazy(() => import("../fragments/antd/timeline.tsx")), 'antd', true)
    registerComponent('Card', '', lazy(() => import("../fragments/antd/card.tsx")), 'antd', true)
    registerComponent('Affix', '', lazy(() => import("../fragments/antd/affix.tsx")), 'antd', true)
    registerComponent('Carousel', '', lazy(() => import("../fragments/antd/carousel.tsx")), 'antd', true)
    registerComponent('Badge', '', lazy(() => import("../fragments/antd/badge.tsx")), 'antd', true)
    registerComponent('Image', '', lazy(() => import("../fragments/antd/image.tsx")), 'antd', true)
    registerComponent('Form', '', lazy(() => import("../fragments/antd/form.tsx")), 'antd', true)
    registerComponent('Select', '', lazy(() => import("../fragments/antd/select.tsx")), 'antd', true)
    registerComponent('InputNumber', '', lazy(() => import("../fragments/antd/inputnumber.tsx")), 'antd', true)
    registerComponent('Tree', '', lazy(() => import("../fragments/antd/tree.tsx")), 'antd', false)
    registerComponent('Watermark', '', lazy(() => import("../fragments/antd/watermark.tsx")), 'antd', true)
    registerComponent('Spin', '', lazy(() => import("../fragments/antd/spin.tsx")), 'antd', true)
    registerComponent('Pagination', '', lazy(() => import("../fragments/antd/pagination.tsx")), 'antd', true)
    registerComponent('Calendar', '', lazy(() => import("../fragments/antd/calendar.tsx")), 'antd', true)
    registerComponent('Anchor', 'Item', lazy(() => import("../fragments/antd/anchor_item.tsx")), 'antd', true)
    registerComponent('Descriptions', 'Item', lazy(() => import("../fragments/antd/descriptions_item.tsx")), 'antd', true)
    registerComponent('Upload', 'UploadFile', lazy(() => import("../fragments/antd/upload_uploadfile.tsx")), 'antd', true)
    registerComponent('Collapse', 'Panel', lazy(() => import("../fragments/antd/collapse_panel.tsx")), 'antd', true)
    registerComponent('Typography', 'Link', lazy(() => import("../fragments/antd/typography_link.tsx")), 'antd', true)
    registerComponent('Typography', 'Paragraph', lazy(() => import("../fragments/antd/typography_paragraph.tsx")), 'antd', true)
    registerComponent('Typography', 'Text', lazy(() => import("../fragments/antd/typography_text.tsx")), 'antd', true)
    registerComponent('Typography', 'Title', lazy(() => import("../fragments/antd/typography_title.tsx")), 'antd', true)
    registerComponent('Input', 'Group', lazy(() => import("../fragments/antd/input_group.tsx")), 'antd', true)
    registerComponent('Input', 'Password', lazy(() => import("../fragments/antd/input_password.tsx")), 'antd', true)
    registerComponent('Input', 'Search', lazy(() => import("../fragments/antd/input_search.tsx")), 'antd', true)
    registerComponent('Input', 'TextArea', lazy(() => import("../fragments/antd/input_textarea.tsx")), 'antd', true)
    registerComponent('Dropdown', 'Button', lazy(() => import("../fragments/antd/dropdown_button.tsx")), 'antd', true)
    registerComponent('Tour', 'Step', lazy(() => import("../fragments/antd/tour_step.tsx")), 'antd', true)
    registerComponent('FloatButton', 'BackTop', lazy(() => import("../fragments/antd/floatbutton_backtop.tsx")), 'antd', true)
    registerComponent('FloatButton', 'Group', lazy(() => import("../fragments/antd/floatbutton_group.tsx")), 'antd', true)
    registerComponent('Layout', 'Content', lazy(() => import("../fragments/antd/layout_content.tsx")), 'antd', true)
    registerComponent('Layout', 'Footer', lazy(() => import("../fragments/antd/layout_footer.tsx")), 'antd', true)
    registerComponent('Layout', 'Header', lazy(() => import("../fragments/antd/layout_header.tsx")), 'antd', true)
    registerComponent('Layout', 'Sider', lazy(() => import("../fragments/antd/layout_sider.tsx")), 'antd', true)
    registerComponent('Table', 'Column', lazy(() => import("../fragments/antd/table_column.tsx")), 'antd', true)
    registerComponent('Table', 'ColumnGroup', lazy(() => import("../fragments/antd/table_columngroup.tsx")), 'antd', true)
    registerComponent('Tag', 'CheckableTag', lazy(() => import("../fragments/antd/tag_checkabletag.tsx")), 'antd', true)
    registerComponent('DatePicker', 'RangePicker', lazy(() => import("../fragments/antd/datepicker_rangepicker.tsx")), 'antd', true)
    registerComponent('Avatar', 'Group', lazy(() => import("../fragments/antd/avatar_group.tsx")), 'antd', true)
    registerComponent('Skeleton', 'Avatar', lazy(() => import("../fragments/antd/skeleton_avatar.tsx")), 'antd', true)
    registerComponent('Skeleton', 'Button', lazy(() => import("../fragments/antd/skeleton_button.tsx")), 'antd', true)
    registerComponent('Skeleton', 'Input', lazy(() => import("../fragments/antd/skeleton_input.tsx")), 'antd', true)
    registerComponent('Skeleton', 'Paragraph', lazy(() => import("../fragments/antd/skeleton_paragraph.tsx")), 'antd', true)
    registerComponent('Skeleton', 'Title', lazy(() => import("../fragments/antd/skeleton_title.tsx")), 'antd', true)
    registerComponent('List', 'Item', lazy(() => import("../fragments/antd/list_item.tsx")), 'antd', true)
    registerComponent('Radio', 'Button', lazy(() => import("../fragments/antd/radio_button.tsx")), 'antd', true)
    registerComponent('Radio', 'Group', lazy(() => import("../fragments/antd/radio_group.tsx")), 'antd', true)
    registerComponent('TimePicker', 'RangePicker', lazy(() => import("../fragments/antd/timepicker_rangepicker.tsx")), 'antd', true)
    registerComponent('Steps', 'Item', lazy(() => import("../fragments/antd/steps_item.tsx")), 'antd', true)
    registerComponent('Checkbox', 'Group', lazy(() => import("../fragments/antd/checkbox_group.tsx")), 'antd', true)
    registerComponent('Button', 'Group', lazy(() => import("../fragments/antd/button_group.tsx")), 'antd', true)
    registerComponent('Statistic', 'Countdown', lazy(() => import("../fragments/antd/statistic_countdown.tsx")), 'antd', true)
    registerComponent('Card', 'Grid', lazy(() => import("../fragments/antd/card_grid.tsx")), 'antd', true)
    registerComponent('Card', 'Meta', lazy(() => import("../fragments/antd/card_meta.tsx")), 'antd', true)
    registerComponent('Badge', 'Ribbon', lazy(() => import("../fragments/antd/badge_ribbon.tsx")), 'antd', true)
    registerComponent('Image', 'PreviewGroup', lazy(() => import("../fragments/antd/image_previewgroup.tsx")), 'antd', true)
    registerComponent('Form', 'Item', lazy(() => import("../fragments/antd/form_item.tsx")), 'antd', true)
    registerComponent('Form', 'List', lazy(() => import("../fragments/antd/form_list.tsx")), 'antd', true)
    registerComponent('Tree', 'DirectoryTree', lazy(() => import("../fragments/antd/tree_directorytree.tsx")), 'antd', false)
    registerComponent('Tree', 'TreeNode', lazy(() => import("../fragments/antd/tree_treenode.tsx")), 'antd', false)
    registerMethod("antd", "notification", notification);
    registerMethod("antd", "message", message);
    registerMethod("antd", "Modal", Modal);
    console.log('antd registered');
  });
}